name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          fetch-tags: true

      - name: Setup 7-Zip
        uses: milliewalky/setup-7-zip@v1

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.3.1'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.16.x'

      - name: Setup MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Prebuild
        shell: pwsh
        run: |
          .\prebuild.ps1

      - name: Build
        shell: pwsh
        run: |
          .\build.ps1

      - name: Bundle
        shell: pwsh
        run: |
          .\bundle-zip.ps1

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./x64/Release/GlosSI-snapshot.zip
          retention-days: 5
